{{- if .Values.notification.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "load-chart.fullname" . }}-notification
  labels:
    {{- include "load-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    {{- with .Values.argocd.notification.syncWave }}
    argocd.argoproj.io/sync-wave: {{ . | quote }}
    {{- end }}
spec:
  backoffLimit: {{ .Values.notification.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.notification.ttlSecondsAfterFinished }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "load-chart.labels" . | nindent 8 }}
        app.kubernetes.io/component: notification
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "load-chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: notification
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.notification.image.repository }}:{{ .Values.notification.image.tag }}"
          imagePullPolicy: {{ .Values.notification.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              echo "===================================="
              echo "Slack Notification - Test Results"
              echo "===================================="
              echo "Application: {{ include "load-chart.fullname" . }}"
              echo "Namespace: {{ .Release.Namespace }}"
              echo ""

              # Wait for test job to complete (success or failure)
              echo "Waiting for test job to complete..."
              TIMEOUT={{ .Values.notification.waitTimeout }}
              ELAPSED=0

              while true; do
                if [ $ELAPSED -ge $TIMEOUT ]; then
                  echo "ERROR: Timeout waiting for test job after ${TIMEOUT} seconds"

                  # Send timeout notification to Slack
                  MESSAGE="❌ *Test Job Timeout*\n\nApplication: \`{{ include "load-chart.fullname" . }}\`\nNamespace: \`{{ .Release.Namespace }}\`\nStatus: Test job did not complete within ${TIMEOUT} seconds\nTimestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

                  curl -X POST {{ .Values.notification.slackWebhookUrl }} \
                    -H 'Content-Type: application/json' \
                    -d "{\"text\": \"${MESSAGE}\"}"

                  exit 1
                fi

                # Check if test job completed successfully
                JOB_COMPLETE=$(kubectl get job {{ include "load-chart.fullname" . }}-test \
                  -n {{ .Release.Namespace }} \
                  -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}' 2>/dev/null || echo "")

                # Check if test job failed
                JOB_FAILED=$(kubectl get job {{ include "load-chart.fullname" . }}-test \
                  -n {{ .Release.Namespace }} \
                  -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}' 2>/dev/null || echo "")

                if [ "$JOB_COMPLETE" = "True" ]; then
                  echo "✓ Test job completed successfully!"

                  # Send success notification to Slack
                  MESSAGE="✅ *Tests Passed Successfully*\n\nApplication: \`{{ include "load-chart.fullname" . }}\`\nNamespace: \`{{ .Release.Namespace }}\`\nStatus: All migration tests passed\n\nVerified:\n• PostgreSQL connectivity\n• Database schema (users, products, orders tables)\n• Sample data integrity\n• Foreign key constraints\n\nTimestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

                  curl -X POST {{ .Values.notification.slackWebhookUrl }} \
                    -H 'Content-Type: application/json' \
                    -d "{\"text\": \"${MESSAGE}\"}"

                  echo ""
                  echo "✓ Success notification sent to Slack"
                  exit 0
                fi

                if [ "$JOB_FAILED" = "True" ]; then
                  echo "✗ Test job failed!"

                  # Get failure details
                  FAILURE_MESSAGE=$(kubectl get job {{ include "load-chart.fullname" . }}-test \
                    -n {{ .Release.Namespace }} \
                    -o jsonpath='{.status.conditions[?(@.type=="Failed")].message}' 2>/dev/null || echo "Unknown error")

                  # Send failure notification to Slack
                  MESSAGE="❌ *Tests Failed*\n\nApplication: \`{{ include "load-chart.fullname" . }}\`\nNamespace: \`{{ .Release.Namespace }}\`\nStatus: Migration tests failed\nReason: ${FAILURE_MESSAGE}\n\nPlease check the test job logs for details:\n\`kubectl logs job/{{ include "load-chart.fullname" . }}-test -n {{ .Release.Namespace }}\`\n\nTimestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

                  curl -X POST {{ .Values.notification.slackWebhookUrl }} \
                    -H 'Content-Type: application/json' \
                    -d "{\"text\": \"${MESSAGE}\"}"

                  echo ""
                  echo "✓ Failure notification sent to Slack"
                  exit 0
                fi

                echo "Test job still running... waiting (${ELAPSED}s/${TIMEOUT}s)"
                sleep 5
                ELAPSED=$((ELAPSED + 5))
              done
          env:
            - name: SLACK_WEBHOOK_URL
              value: {{ .Values.notification.slackWebhookUrl | quote }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
